development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3

test:
  adapter: postgresql
  encoding: utf8
  database: grokphoto-test

production:
  adapter: postgresql
  encoding: utf8
  database: grokphoto-production